### ISSUE TITLE
Which SD webui version is supported?

### ISSUE THREAD

**Issue by fouvy** [John-WL/sd-webui-inpaint-background#11]
I got an error from webui forge version. Here is message: 

```
Python 3.9.12 (main, Apr  5 2022, 06:56:58) 
[GCC 7.5.0]
Version: f0.0.1-1.7.0
Commit hash: <none>
Launching Web UI with arguments: --xformers --listen --enable-insecure-extension-access --api
Total VRAM 24260 MB, total RAM 1019411 MB
xformers version: 0.0.20
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3090 : native
VAE dtype: torch.bfloat16
Using xformers cross attention
==============================================================================
You are running torch 2.0.1+cu118.
The program is tested to work with torch 2.1.2.
To reinstall the desired version, run with commandline flag --reinstall-torch.
Beware that this will cause a lot of large files to be downloaded, as well as
there are reports of issues with training tab on the latest version.

Use --skip-version-check commandline argument to disable this check.
==============================================================================
=================================================================================
You are running xformers 0.0.20.
The program is tested to work with xformers 0.0.23.post1.
To reinstall the desired version, run with commandline flag --reinstall-xformers.

Use --skip-version-check commandline argument to disable this check.
=================================================================================
ControlNet preprocessor location: /mnt/data1/ml/webui/stable-diffusion-webui-forge/models/ControlNetPreprocessor
[-] ADetailer: Failed to load model 'face_yolov8n.pt' from huggingface
[-] ADetailer initialized. version: 24.4.2, num models: 16
[sdwi2iextender] Applying img2img patch
Loading weights [2d5af23726] from /mnt/data1/ml/webui/stable-diffusion-webui-forge/models/Stable-diffusion/realismEngineSDXL_v30VAE.safetensors
2024-05-07 09:14:53,352 - AnimateDiff - INFO - Injecting LCM to UI.
2024-05-07 09:14:53,941 - ControlNet - INFO - ControlNet UI callback registered.
2024-05-07 09:14:53,977 - AnimateDiff - INFO - Hacking i2i-batch.
Traceback (most recent call last):
  File "/mnt/data1/ml/webui/stable-diffusion-webui-forge/launch.py", line 48, in <module>
    main()
  File "/mnt/data1/ml/webui/stable-diffusion-webui-forge/launch.py", line 44, in main
    start()
  File "/mnt/data1/ml/webui/stable-diffusion-webui-forge/modules/launch_utils.py", line 512, in start
    webui.webui()
  File "/mnt/data1/ml/webui/stable-diffusion-webui-forge/webui.py", line 68, in webui
    shared.demo = ui.create_ui()
  File "/mnt/data1/ml/webui/stable-diffusion-webui-forge/modules/ui.py", line 1107, in create_ui
    loadsave = ui_loadsave.UiLoadsave(cmd_opts.ui_config_file)
  File "/mnt/data1/ml/webui/stable-diffusion-webui-forge/venv/lib/python3.9/site-packages/sdwi2iextender/lib/img2img_tab_extender.py", line 164, in hijack__init__
    Img2imgTabExtender.instantiate_custom_tabs()
  File "/mnt/data1/ml/webui/stable-diffusion-webui-forge/venv/lib/python3.9/site-packages/sdwi2iextender/lib/img2img_tab_extender.py", line 96, in instantiate_custom_tabs
    cls.setup_navigation_events(img2img_tabs)
  File "/mnt/data1/ml/webui/stable-diffusion-webui-forge/venv/lib/python3.9/site-packages/sdwi2iextender/lib/img2img_tab_extender.py", line 111, in setup_navigation_events
    block_data_iterator = zip(img2img_tabs, padded_tab_data_list, strict=True)
TypeError: zip() takes no keyword arguments
model_type EPS
UNet ADM Dimension 2816
```

**Comment by John-WL** [comment]
Huh, is the extension up to date? The message printed in the console probably indicates that it is not. 

The extension should work fine with forge. It is designed to work for both 1.8 and 1.9 at the moment, and should have forge compatibility implemented. 

What happens if you run `pip show sdwi2iextender`?

**Comment by John-WL** [comment]
Closing this for now as no answer from OP, and I assume the issue was just that the extension was not updated. 

Please reopen it if you belive it's still relevant.
