### ISSUE TITLE
'Options' object has no attribute 'img2img_editor_height'

### ISSUE THREAD

**Issue by Sarcasticest** [John-WL/sd-webui-inpaint-background#18]
Hi,

I'm using forge and I'm receiving this error:

```
Traceback (most recent call last):
  File "C:\Users\Name\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Users\Name\AppData\Local\Programs\Python\Python310\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Name\AI\Forge\stable-diffusion-webui-forge\webui.py", line 84, in webui_worker
    shared.demo = ui.create_ui()
  File "C:\Users\Name\AI\Forge\stable-diffusion-webui-forge\modules\ui.py", line 952, in create_ui
    loadsave = ui_loadsave.UiLoadsave(cmd_opts.ui_config_file)
  File "C:\Users\Name\AI\Forge\stable-diffusion-webui-forge\venv\lib\site-packages\sdwi2iextender\lib\img2img_tab_extender.py", line 164, in hijack__init__
    Img2imgTabExtender.instantiate_custom_tabs()
  File "C:\Users\Name\AI\Forge\stable-diffusion-webui-forge\venv\lib\site-packages\sdwi2iextender\lib\img2img_tab_extender.py", line 90, in instantiate_custom_tabs
    custom_tab_object.tab()
  File "C:\Users\Name\AI\Forge\stable-diffusion-webui-forge\extensions\sd-webui-inpaint-background\lib_inpaint_background\ui.py", line 36, in tab
    self.inpaint_visual_mask_component = gr.Image(label="Background mask", interactive=False, type="pil", elem_id="mask_inpaint_background", tool="sketch", height=opts.img2img_editor_height, brush_color=opts.img2img_inpaint_mask_brush_color)
  File "C:\Users\Name\AI\Forge\stable-diffusion-webui-forge\modules\options.py", line 142, in __getattr__
    return super(Options, self).__getattribute__(item)
AttributeError: 'Options' object has no attribute 'img2img_editor_height'

**Comment by PladsElsker** [comment]
Sadly, I do not intend to support forge anymore. It's a lot of work for me. I encourage you to look into the code and figure out the problem.

**Comment by PladsElsker** [comment]
You can try to do `pip install --upgrade sdwi2iextender` in case the library is not up to date anymore, but the problem may be something else as well.

**Comment by Sarcasticest** [comment]
Understood, thank you for your reply.
