### ISSUE TITLE
Forge Version Support

### ISSUE THREAD

**Issue by WaGi-Coding** [John-WL/sd-webui-inpaint-background#7]
Can you make it support SD WebUI Forge version? I guess that sd extender broke it, but not sure, never tried if before today.

Greetings

**Comment by John-WL** [comment]
Thank you for reporting the issue. 

I haven't tested on Forge, there are too many UIs nowadays. I rely on issues like these for other UIs. 

Can you show the error in the console? 

I am the maintainer of sdwi2iextender. I have recently made an update in an attempt to get a working patch for both 1.8 and 1.9 because release 1.9 will break the previous hijacking.

**Comment by WaGi-Coding** [comment]
> Thank you for reporting the issue.
> 
> I haven't tested on Forge, there are too many UIs nowadays. I rely on issues like these for other UIs.
> 
> Can you show the error in the console?
> 
> I am the maintainer of sdwi2iextender. I have recently made an update in an attempt to get a working patch for both 1.8 and 1.9 because release 1.9 will break the previous hijacking.

Hey, thanks for your reply. I was just giving forge a go because i can really speed up generation on my oold 2070super with it, like 8 seconds instead of 13 for lighting. So Forge should adapt instead i guess, if even possible?

Anyway, here is the console output:
```
Launching Web UI with arguments: --ckpt-dir D:/Users/Taki/SD/1.8/models --cuda-stream --pin-shared-memory
Total VRAM 8192 MB, total RAM 32689 MB
Set vram state to: NORMAL_VRAM
Always pin shared GPU memory
Device: cuda:0 NVIDIA GeForce RTX 2070 SUPER : native
Hint: your device supports --cuda-malloc for potential speed improvements.
VAE dtype: torch.float32
CUDA Stream Activated:  True
Using pytorch cross attention
ControlNet preprocessor location: C:\Users\Wagi\SD_FORGE\webui\models\ControlNetPreprocessor
[sdwi2iextender] Applying img2img patch
*** Error loading script: inpaint_background.py
    Traceback (most recent call last):
      File "C:\Users\Wagi\SD_FORGE\webui\modules\scripts.py", line 544, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "C:\Users\Wagi\SD_FORGE\webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "C:\Users\Wagi\SD_FORGE\webui\extensions\sd-webui-inpaint-background\scripts\inpaint_background.py", line 5, in <module>
        setup_script_callbacks(BackgroundGlobals.is_extension_enabled)
      File "C:\Users\Wagi\SD_FORGE\webui\extensions\sd-webui-inpaint-background\lib_inpaint_background\webui_callbacks.py", line 10, in setup_script_callbacks
        register_operation_mode(InpaintBackgroundTab)
      File "C:\Users\Wagi\SD_FORGE\system\python\lib\site-packages\sdwi2iextender\lib\img2img_tab_extender.py", line 18, in register_operation_mode
        enable_tab_extender()
      File "C:\Users\Wagi\SD_FORGE\system\python\lib\site-packages\sdwi2iextender\lib\one_time_callable.py", line 5, in wrapper
        return func(*args, **kwargs)
      File "C:\Users\Wagi\SD_FORGE\system\python\lib\site-packages\sdwi2iextender\lib\img2img_tab_extender.py", line 157, in enable_tab_extender
        activate_injector()
      File "C:\Users\Wagi\SD_FORGE\system\python\lib\site-packages\sdwi2iextender\lib\one_time_callable.py", line 5, in wrapper
        return func(*args, **kwargs)
      File "C:\Users\Wagi\SD_FORGE\system\python\lib\site-packages\sdwi2iextender\lib\img2img_component_injector.py", line 17, in activate_injector
        activate_generation_component_injector()
      File "C:\Users\Wagi\SD_FORGE\system\python\lib\site-packages\sdwi2iextender\lib\one_time_callable.py", line 5, in wrapper
        return func(*args, **kwargs)
      File "C:\Users\Wagi\SD_FORGE\system\python\lib\site-packages\sdwi2iextender\lib\img2img_component_injector.py", line 112, in activate_generation_component_injector
        add_nasty_patches()
      File "C:\Users\Wagi\SD_FORGE\system\python\lib\site-packages\sdwi2iextender\lib\img2img_component_injector.py", line 133, in add_nasty_patches
        last_ast_if.orelse[:] = ast.parse(code_patch).body[0:1]
    AttributeError: 'NoneType' object has no attribute 'orelse'

---
Loading weights [58ed423904] from D:\Users\Taki\SD\1.8\models\Stable-diffusion\SD_XL\APRIL 2024\LIGTHING\copaxTimelessxlSDXL1_v11Lightning.safetensors
C:\Users\Wagi\SD_FORGE\webui\scripts\CropWithMask.py:61: GradioDeprecationWarning: Usage of gradio.inputs is deprecated, and will not be supported in the future, please import your component from gradio.components
  mask_upload = gr.inputs.Image(label="Upload Mask Image", type="pil", )
C:\Users\Wagi\SD_FORGE\webui\modules\gradio_extensons.py:25: GradioDeprecationWarning: `optional` parameter is deprecated, and it has no effect
  res = original_IOComponent_init(self, *args, **kwargs)
2024-04-12 18:58:52,027 - ControlNet - INFO - ControlNet UI callback registered.
Running on local URL:  http://127.0.0.1:7860
```

Greetings

**Comment by John-WL** [comment]
Hmm, I might need to make a separate patching behavior for SD Forge. It definitely is sdwi2iextender's job to adapt here.

**Comment by John-WL** [comment]
Should be fixed now!

**Comment by WaGi-Coding** [comment]
> Should be fixed now!

many thanks for your quick fix, much appreciated. Many thanks!
Greetings
